export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: string;
  subcategory?: string;
  brand: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  isOnSale: boolean;
  isNew: boolean;
  isPickupAvailable: boolean;
  isDeliveryAvailable: boolean;
  tags: string[];
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Pidilite Fevistik Super Glue Stick',
    description: 'Strong adhesive glue stick for paper, cardboard, and fabric. Perfect for arts and crafts projects.',
    price: 3.98,
    originalPrice: 4.98,
    image: 'https://www.bigbasket.com/media/uploads/p/m/1213419_3-pidilite-fevistik-super-glue-stick.jpg',
    category: 'Office Products',
    subcategory: 'Adhesives',
    brand: 'Pidilite',
    rating: 4.5,
    reviewCount: 1247,
    inStock: true,
    isOnSale: true,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'glue', 'adhesive', 'crafts'],
  },
  {
    id: '2',
    name: 'Solo Multi Pen Holder Mix Stationary Storage',
    description: 'Organized desk organizer with multiple compartments for pens, pencils, and office supplies.',
    price: 12.99,
    image: 'https://www.bigbasket.com/media/uploads/p/m/40286067_1-solo-multi-pen-holder-mix-stationary-storage-tidy-desk-organizer-box.jpg',
    category: 'Office Products',
    subcategory: 'Desk Organizers',
    brand: 'Solo',
    rating: 4.3,
    reviewCount: 892,
    inStock: true,
    isOnSale: false,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'organizer', 'desk', 'storage'],
  },
  {
    id: '3',
    name: 'Classmate Drawing Book Unruled 40 Pages',
    description: 'High-quality drawing paper for artists and students. Perfect for sketching and artwork.',
    price: 2.49,
    originalPrice: 3.49,
    image: 'https://www.bigbasket.com/media/uploads/p/m/1204291_2-classmate-drawing-book-unruled-40-pages.jpg',
    category: 'Office Products',
    subcategory: 'Paper',
    brand: 'Classmate',
    rating: 4.8,
    reviewCount: 2156,
    inStock: true,
    isOnSale: true,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'paper', 'drawing', 'art'],
  },
  {
    id: '4',
    name: 'SE7EN A4 Size Regular Colour Paper',
    description: 'Assorted colored paper for arts and crafts. Bright colors for creative projects.',
    price: 4.99,
    originalPrice: 6.99,
    image: 'https://www.bigbasket.com/media/uploads/p/m/40280995_1-se7en-a4-size-regular-colour-paper-for-arts-crafts-assorted.jpg',
    category: 'Office Products',
    subcategory: 'Paper',
    brand: 'SE7EN',
    rating: 4.6,
    reviewCount: 1843,
    inStock: true,
    isOnSale: true,
    isNew: false,
    isPickupAvailable: false,
    isDeliveryAvailable: true,
    tags: ['office', 'paper', 'colored', 'crafts'],
  },
  {
    id: '5',
    name: 'JK Copier A4 Paper 75 GSM',
    description: 'High-quality copier paper for printing and photocopying. 500 sheets per pack.',
    price: 8.97,
    originalPrice: 12.97,
    image: 'https://www.bigbasket.com/media/uploads/p/m/160499_4-jk-copier-a4-paper-75-gsm.jpg',
    category: 'Office Products',
    subcategory: 'Paper',
    brand: 'JK',
    rating: 4.4,
    reviewCount: 967,
    inStock: true,
    isOnSale: true,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'paper', 'copier', 'printing'],
  },
  {
    id: '6',
    name: 'CS Medium Paper Label Sticker',
    description: 'Adhesive labels for organizing and labeling. Perfect for office and home use.',
    price: 3.49,
    image: 'https://www.bigbasket.com/media/uploads/p/m/40324286_1-cs-medium-paper-label-sticker.jpg',
    category: 'Office Products',
    subcategory: 'Labels',
    brand: 'CS',
    rating: 4.2,
    reviewCount: 2156,
    inStock: true,
    isOnSale: false,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'labels', 'stickers', 'organizing'],
  },
  {
    id: '7',
    name: 'Faber Castell Wax Crayon Regular Long',
    description: 'Extra smooth wax crayons in 12 shades. Perfect for children and artists.',
    price: 5.99,
    originalPrice: 7.99,
    image: 'https://www.bigbasket.com/media/uploads/p/m/1229648_1-faber-castell-wax-crayon-regular-long-75-mm-12-shades-extra-smooth.jpg',
    category: 'Office Products',
    subcategory: 'Art Supplies',
    brand: 'Faber Castell',
    rating: 4.9,
    reviewCount: 743,
    inStock: true,
    isOnSale: true,
    isNew: false,
    isPickupAvailable: false,
    isDeliveryAvailable: true,
    tags: ['office', 'crayons', 'art', 'children'],
  },
  {
    id: '8',
    name: 'Faber Castell Writing Marking Kit',
    description: 'Complete writing kit with markers and pens for professional use.',
    price: 15.99,
    originalPrice: 19.99,
    image: 'https://www.bigbasket.com/media/uploads/p/m/40005308_6-faber-castell-writing-marking-kit.jpg',
    category: 'Office Products',
    subcategory: 'Writing Supplies',
    brand: 'Faber Castell',
    rating: 4.3,
    reviewCount: 3421,
    inStock: true,
    isOnSale: true,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'markers', 'writing', 'professional'],
  },
  {
    id: '9',
    name: 'Faber Castell My First Series School Essentials',
    description: 'Complete school essentials kit for young learners. Includes pencils, erasers, and sharpeners.',
    price: 9.99,
    originalPrice: 14.99,
    image: 'https://www.bigbasket.com/media/uploads/p/m/40285475_2-faber-castell-my-first-series-school-essentials-574104.jpg',
    category: 'Office Products',
    subcategory: 'School Supplies',
    brand: 'Faber Castell',
    rating: 4.7,
    reviewCount: 1567,
    inStock: true,
    isOnSale: true,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'school', 'essentials', 'children'],
  },
  {
    id: '10',
    name: 'Polo Junior Gift Kit',
    description: 'Perfect gift kit for children with various art and craft supplies.',
    price: 12.49,
    image: 'https://www.bigbasket.com/media/uploads/p/m/40322838_1-polo-junior-gift-kit.jpg',
    category: 'Office Products',
    subcategory: 'Gift Sets',
    brand: 'Polo',
    rating: 4.5,
    reviewCount: 892,
    inStock: true,
    isOnSale: false,
    isNew: true,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'gift', 'children', 'crafts'],
  },
  {
    id: '11',
    name: 'Classmate Spin 07 Ball Pen Blue',
    description: 'Smooth writing ball pen with ergonomic design. Perfect for daily use.',
    price: 1.99,
    image: 'https://www.bigbasket.com/media/uploads/p/m/40325468_1-classmate-spin-07-ball-pen-blue.jpg',
    category: 'Office Products',
    subcategory: 'Pens',
    brand: 'Classmate',
    rating: 4.6,
    reviewCount: 2341,
    inStock: true,
    isOnSale: false,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'pen', 'writing', 'blue'],
  },
  {
    id: '12',
    name: 'APSARA EZ Grip Extra Dark Pencil',
    description: 'Extra dark pencil for smooth writing and drawing. Ergonomic grip for comfort.',
    price: 2.49,
    image: 'https://www.bigbasket.com/media/uploads/p/m/40188557_4-apsara-ez-grip-extra-dark-pencil-for-smooth-writing.jpg',
    category: 'Office Products',
    subcategory: 'Pencils',
    brand: 'APSARA',
    rating: 4.4,
    reviewCount: 1876,
    inStock: true,
    isOnSale: false,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'pencil', 'writing', 'dark'],
  },
  {
    id: '13',
    name: 'Pidilite Fevicryl Pearl Kit',
    description: 'Pearl effect paint kit for creative projects and crafts.',
    price: 6.99,
    originalPrice: 8.99,
    image: 'https://www.bigbasket.com/media/uploads/p/m/40087818_4-pidilite-fevicryl-pearl-kit.jpg',
    category: 'Office Products',
    subcategory: 'Art Supplies',
    brand: 'Pidilite',
    rating: 4.3,
    reviewCount: 945,
    inStock: true,
    isOnSale: true,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'paint', 'pearl', 'crafts'],
  },
  {
    id: '14',
    name: 'Classmate Gel Pen Blue Octane Colour Burst',
    description: 'Smooth gel pen with vibrant blue ink. Perfect for writing and drawing.',
    price: 3.49,
    image: 'https://www.bigbasket.com/media/uploads/p/m/40125808_4-classmate-gel-pen-blue-octane-colour-burst.jpg',
    category: 'Office Products',
    subcategory: 'Pens',
    brand: 'Classmate',
    rating: 4.5,
    reviewCount: 1234,
    inStock: true,
    isOnSale: false,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'gel-pen', 'blue', 'writing'],
  },
  {
    id: '15',
    name: 'Maped Ruler 30 cm Unbreakable',
    description: 'Durable unbreakable ruler for precise measurements. Perfect for school and office.',
    price: 4.99,
    image: 'https://www.bigbasket.com/media/uploads/p/m/1229637_1-maped-ruler-30-cm-unbreakable-for-measurement.jpg',
    category: 'Office Products',
    subcategory: 'Measuring Tools',
    brand: 'Maped',
    rating: 4.7,
    reviewCount: 678,
    inStock: true,
    isOnSale: false,
    isNew: false,
    isPickupAvailable: true,
    isDeliveryAvailable: true,
    tags: ['office', 'ruler', 'measuring', 'durable'],
  },
];

export const categories = [
  'All',
  'Office Products',
  'Electronics',
  'Clothing & Shoes',
  'Home & Garden',
  'Toys & Games',
  'Sports & Outdoors',
  'Health & Beauty',
  'Automotive',
  'Baby',
  'Pet Supplies',
  'Grocery',
  'Pharmacy',
  'Jewelry',
  'Movies & TV',
  'Books',
  'Video Games',
  'Tools & Hardware',
  'Patio & Garden',
  'Arts & Crafts',
];

export const getProductsByCategory = (category: string) => {
  if (category === 'All') return products;
  return products.filter(product => product.category === category);
};

export const getProductsOnSale = () => {
  return products.filter(product => product.isOnSale);
};

export const getNewProducts = () => {
  return products.filter(product => product.isNew);
};

export const searchProducts = (query: string) => {
  const lowercaseQuery = query.toLowerCase();
  return products.filter(product =>
    product.name.toLowerCase().includes(lowercaseQuery) ||
    product.description.toLowerCase().includes(lowercaseQuery) ||
    product.brand.toLowerCase().includes(lowercaseQuery) ||
    product.tags.some(tag => tag.toLowerCase().includes(lowercaseQuery))
  );
};

export default products; 